en_dict = {
    "commander_power": "Commander Power",
    "commander_kill": "Commander Kill",
    "commander_city": "Commander City",
    "commander_officer": "Commander Officer",
    "commander_titan": "Commander Titan",
    "commander_island" : "Commander Island",
    "commander_merit": "Commander Merit",
    "commander_level": "Commander Level",
    "commander_ke_frenzy": "Frenzy Kill Event",
    "commander_sc_frenzy": "Frenzy Event",
    "commander_ke_void": "Void Kill Event",
    "commander_sc_void": "Void Event",
    "alliance_power": "Alliance Power",
    "alliance_kill": "Alliance Kill",
    "alliance_territory": "Alliance Territory",
    "alliance_elite": "Alliance Elite",
    "alliance_sc_frenzy": "Frenzy Event",
    "alliance_sc_void": "Void Event",
    "Commander Name": "Commander Name",
    "Alliance Name": "Alliance Name",
    "Commander Ranking": "Commander ranking",
    "Alliance Ranking": "Alliance ranking",
    "Strongest Commander": "Strongest Commander",
    "Event": "Event",
    "Date": "Date",
    "Opponent": "Opponent",
    "Opponent score": "Opponent score",
    "Nation score": "Nation score",
    "Result": "Result",
    "Win": "Win",
    "Lost": "Lost",
    "Strongest Commander Events": "Strongest Commander Events",
    "void": "Void",
    "frenzy": "Frenzy",
    "Search: ": "Search: ",
    "Ranking: ": "Ranking: ",
    "Clear graph": "Clear graph",
    "Reset graph": "Reset graph",
    "Clear name": "Clear name",
    "Void cycle update": "Void cycle update",
    "Frenzy cycle update": "Frenzy cycle update",
    "name : xxx kills": "{0} : {1} kills",
    "name : merit_rank": "{0} : {1}",
    "name : city_level": "{0} : {1}",
    "name reached xxx officer power": "{0} reached {1} officer power",
    "name reached xxx titan power": "{0} reached {1} titan power",
    "Officer power": "Officer power",
    "Titan power": "Titan power",
    "City level upgrade": "City level upgrade",
    "Promotions": "Promotions",
    "Top killers": "Top killers",
    "Recruit" : "Recruit",
    "Private" : "Private",
    "Private First Class" : "Private First Class",
    "Sergeant" : "Sergeant",
    "Master Sergeant": "Master Sergeant",
    "Warrant Officer" : "Warrant Officer",
    "Second Lieutenant" : "Second Lieutenant",
    "First Lieutenant" : "First Lieutenant",
    "Captain" : "Captain",
    "Major" : "Major",
    "Lieutenant Colonel" : "Lieutenant Colonel",
    "Colonel" : "Colonel",
    "Brigadier" : "Brigadier",
    "General" : "General",
    "General of the Army" : "General of the Army",
    "No data for this cycle": "No data for this cycle",
}