es_dict={    'commander_power': 'Comandante de poder',
    'commander_kill': 'Comandante matar',
    'commander_city': 'Comandante de la ciudad',
    'commander_officer': 'Comandante',
    'commander_titan': 'Comandante titán',
    'commander_island': 'Isla Comandante',
    'commander_merit': 'Comandante mérito',
    'commander_level': 'Nivel de comandante',
    'commander_ke_frenzy': 'Evento de matar frenesí',
    'commander_sc_frenzy': 'Evento de frenesí',
    'commander_ke_void': 'Evento de matar vacío',
    'commander_sc_void': 'Evento vacío',
    'alliance_power': 'Poder de la alianza',
    'alliance_kill': 'Mata de alianza',
    'alliance_territory': 'Territorio de la Alianza',
    'alliance_elite': 'Elianza Elite',
    'alliance_sc_frenzy': 'Evento de frenesí',
    'alliance_sc_void': 'Evento vacío',
    'Commander Name': 'Nombre del comandante',
    'Alliance Name': 'Nombre de la alianza',
    'Commander Ranking': 'Clasificación de comandantes',
    'Alliance Ranking': 'Clasificación de la alianza',
    'Strongest Commander': 'El comandante más fuerte',
    'Event': 'Evento',
    'Date': 'Fecha',
    'Opponent': 'Adversario',
    'Opponent score': 'Puntaje de oponente',
    'Nation score': 'Puntaje de nación',
    'Result': 'Resultado',
    'Win': 'Ganar',
    'Lost': 'Perdido',
    'Strongest Commander Events': 'Eventos del comandante más fuerte',
    'void': 'Vacío',
    'frenzy': 'Frenesí',
    'Search: ': 'Buscar:',
    'Ranking: ': 'Clasificación:',
    'Clear graph': 'Gráfico de claro',
    'Reset graph': 'Restablecer gráfico',
    'Clear name': 'Eliminar el nombre',
    'Void cycle update': 'Actualización del ciclo vacío',
    'Frenzy cycle update': 'Actualización del ciclo de frenesí',
    'name : xxx kills': '{0}: {1} mata',
    'name : merit_rank': '{0}: {1}',
    'name : city_level': '{0}: {1}',
    'name reached xxx officer power': '{0} alcanzó {1} poder oficial',
    'name reached xxx titan power': '{0} alcanzado {1} Titan Power',
    'Officer power': 'Poder de oficial',
    'Titan power': 'Titan Power',
    'City level upgrade': 'Actualización de nivel de ciudad',
    'Promotions': 'Promociones',
    'Top killers': 'Los mejores asesinos',
    'Recruit': 'Recluta',
    'Private': 'Privado',
    'Private First Class': 'Primera clase privada',
    'Sergeant': 'Sargento',
    'Master Sergeant': 'Sargento Maestro',
    'Warrant Officer': 'Oficial de captura',
    'Second Lieutenant': 'Alférez',
    'First Lieutenant': 'Primer teniente',
    'Captain': 'Capitán',
    'Major': 'Importante',
    'Lieutenant Colonel': 'teniente coronel',
    'Colonel': 'Coronel',
    'Brigadier': 'Brigadier',
    'General': 'General',
    'General of the Army': 'General del Ejército',
    'No data for this cycle': 'No hay datos para este ciclo',
};