fr_dict={
    'commander_power': 'Puissance de Commandant',
    'commander_kill': 'Victimes de Commandant',
    'commander_city': 'Ville de Commandant',
    'commander_officer': 'Officier de Commandant',
    'commander_titan': 'Titan de Commandant',
    'commander_island': 'Île de Commandant',
    'commander_merit': 'Mérite de Commandant',
    'commander_level': 'Niveau du commandant',
    'commander_ke_frenzy': 'Frénésie Kill Event',
    'commander_sc_frenzy': 'Frénésie',
    'commander_ke_void': 'Vide Kill Event',
    'commander_sc_void': 'Vide',
    'alliance_power': 'Puissance d\'Alliance',
    'alliance_kill': 'Vicitmes d\'Alliance',
    'alliance_territory': 'Territoire d\'Alliance',
    'alliance_elite': 'Rang guerre d\'élite',
    'alliance_sc_frenzy': 'Frénésie',
    'alliance_sc_void': 'Vide',
    'Commander Name': 'Nom de Commandant',
    'Alliance Name': 'Nom d\'Alliance',
    'Commander Ranking': 'Classement de Commandant',
    'Alliance Ranking': 'Classement d\'Alliance',
    'Strongest Commander': 'Commandant le plus fort',
    'Event': 'Événement',
    'Date': 'Date',
    'Opponent': 'Adversaire',
    'Opponent score': 'Score Adversaire',
    'Nation score': 'Score Nation',
    'Result': 'Résultat',
    'Win': 'Gagné',
    'Lost': 'Perdu',
    'Strongest Commander Events': 'Comandant le plus fort',
    'void': 'Annuler',
    'frenzy': 'Frénésie',
    'Search: ': 'Recherche:',
    'Ranking: ': 'Classement:',
    'Clear graph': 'Effacer graphique',
    'Reset graph': 'Réinitialiser graphique',
    'Clear name': 'Effacer nom',
    'Void cycle update': 'Nouveautés pendant ce cycle du vide',
    'Frenzy cycle update': 'Nouveautés pendant ce cycle de frénésie',
    'name : xxx kills': '{0}: {1} victimes',
    'name : merit_rank': '{0}: {1}',
    'name : city_level': '{0}: {1}',
    'name reached xxx officer power': '{0} a atteint {1} de puissance d\'officiers',
    'name reached xxx titan power': '{0} a atteint {1} de puissance de titans',
    'Officer power': 'Puissance d\'officiers',
    'Titan power': 'Puissance des titans',
    'City level upgrade': 'Mise à niveau de la ville',
    'Promotions': 'Promotions',
    'Top killers': 'Les meilleurs tueurs',
    'Recruit': 'Recrue',
    'Private': 'Caporal',
    'Private First Class': 'Caporal Chef',
    'Sergeant': 'Sergent',
    'Master Sergeant': 'Sergent Chef',
    'Warrant Officer': 'Adjudant',
    'Second Lieutenant': 'Sous lieutenant',
    'First Lieutenant': 'Lieutenant',
    'Captain': 'Capitaine',
    'Major': 'Majore',
    'Lieutenant Colonel': 'Lieutenant Colonel',
    'Colonel': 'Colonel',
    'Brigadier': 'Général de Brigade',
    'General': 'Général de Division',
    'General of the Army': 'Général des Armées',
    'No data for this cycle': 'Aucune donnée pour ce cycle',
};