ja_dict={    'commander_power': '司令官の力',
    'commander_kill': '司令官は殺します',
    'commander_city': '司令官シティ',
    'commander_officer': '司令官',
    'commander_titan': '司令官タイタン',
    'commander_island': '司令官',
    'commander_merit': '司令官のメリット',
    'commander_level': '司令官レベル',
    'commander_ke_frenzy': 'Frenzy Killイベント',
    'commander_sc_frenzy': '熱狂的なイベント',
    'commander_ke_void': 'ボイドキルイベント',
    'commander_sc_void': 'ボイドイベント',
    'alliance_power': 'アライアンスパワー',
    'alliance_kill': 'アライアンスキル',
    'alliance_territory': 'アライアンスの領土',
    'alliance_elite': 'アライアンスエリート',
    'alliance_sc_frenzy': '熱狂的なイベント',
    'alliance_sc_void': 'ボイドイベント',
    'Commander Name': '司令官名',
    'Alliance Name': 'アライアンス名',
    'Commander Ranking': '司令官のランキング',
    'Alliance Ranking': 'アライアンスランキング',
    'Strongest Commander': '最強の司令官',
    'Event': 'イベント',
    'Date': '日にち',
    'Opponent': '相手',
    'Opponent score': '対戦相手のスコア',
    'Nation score': 'ネーションスコア',
    'Result': '結果',
    'Win': '勝つ',
    'Lost': '失った',
    'Strongest Commander Events': '最強の司令官イベント',
    'void': '空所',
    'frenzy': '狂乱',
    'Search: ': '検索：',
    'Ranking: ': 'ランキング：',
    'Clear graph': 'クリアグラフ',
    'Reset graph': 'グラフをリセットします',
    'Clear name': '名前を削除します',
    'Void cycle update': 'ボイドサイクルアップデート',
    'Frenzy cycle update': '狂乱サイクルの更新',
    'name : xxx kills': '{0}：{1}キル',
    'name : merit_rank': '{0}：{1}',
    'name : city_level': '{0}：{1}',
    'name reached xxx officer power': '{0} {1}役員の権限に到達しました',
    'name reached xxx titan power': '{0} {1}タイタンパワーに到達しました',
    'Officer power': '役員の権力',
    'Titan power': 'タイタンパワー',
    'City level upgrade': '市レベルのアップグレード',
    'Promotions': 'プロモーション',
    'Top killers': 'トップキラー',
    'Recruit': 'リクルート',
    'Private': 'プライベート',
    'Private First Class': '一士',
    'Sergeant': '軍曹',
    'Master Sergeant': '曹長',
    'Warrant Officer': '准尉',
    'Second Lieutenant': '少尉',
    'First Lieutenant': '中尉',
    'Captain': 'キャプテン',
    'Major': '選考科目',
    'Lieutenant Colonel': '中佐',
    'Colonel': '大佐',
    'Brigadier': '准将',
    'General': '全般的',
    'General of the Army': '陸軍将軍',
    'No data for this cycle': 'このサイクルのデータはありません',
};