ko_dict={    'commander_power': '힘',
    'commander_kill': '죽이다',
    'commander_city': '도시',
    'commander_officer': '장교',
    'commander_titan': '타이탄',
    'commander_island': '섬',
    'commander_merit': '장점',
    'commander_level': '수준',
    'commander_ke_frenzy': '열광적 인 킬 이벤트',
    'commander_sc_frenzy': '열풍 이벤트',
    'commander_ke_void': '무효 킬 이벤트',
    'commander_sc_void': '무효 이벤트',
    'alliance_power': '힘',
    'alliance_kill': '죽이다',
    'alliance_territory': '지역',
    'alliance_elite': '엘리트',
    'alliance_sc_frenzy': '열풍 이벤트',
    'alliance_sc_void': '무효 이벤트',
    'Commander Name': '사령관 이름',
    'Alliance Name': '동맹 이름',
    'Commander Ranking': '사령관 순위',
    'Alliance Ranking': '동맹 순위',
    'Strongest Commander': '가장 강력한 사령관',
    'Event': '이벤트',
    'Date': '날짜',
    'Opponent': '상대',
    'Opponent score': '상대 점수',
    'Nation score': '국가 점수',
    'Result': '결과',
    'Win': '이기다',
    'Lost': '잃어버린',
    'Strongest Commander Events': '가장 강력한 사령관 행사',
    'void': '무효의',
    'frenzy': '격분',
    'Search: ': '찾다:',
    'Ranking: ': '순위:',
    'Clear graph': '명확한 그래프',
    'Reset graph': '그래프를 재설정하십시오',
    'Clear name': '이름 삭제',
    'Void cycle update': '무효주기 업데이트',
    'Frenzy cycle update': '열풍주기 업데이트',
    'name : xxx kills': '{0} : {1} 킬',
    'name : merit_rank': '{0} : {1}',
    'name : city_level': '{0} : {1}',
    'name reached xxx officer power': '{0}은 {1} 전력에 도달했습니다',
    'name reached xxx titan power': '{0}은 {1} 전력에 도달했습니다',
    'Officer power': '장교 권력',
    'Titan power': '타이탄의 힘',
    'City level upgrade': '도시 수준 업그레이드',
    'Promotions': '프로모션',
    'Top killers': '최고의 살인자',
    'Recruit': '모집',
    'Private': '사적인',
    'Private First Class': '일등병',
    'Sergeant': '중사',
    'Master Sergeant': '상사',
    'Warrant Officer': '준위',
    'Second Lieutenant': '두 번째 중위',
    'First Lieutenant': '중위',
    'Captain': '선장',
    'Major': '주요한',
    'Lieutenant Colonel': '중령',
    'Colonel': '대령',
    'Brigadier': '준장',
    'General': '일반적인',
    'General of the Army': '군대의 장군',
    'No data for this cycle': '이주기에 대한 데이터가 없습니다',
    'Commander Strength': '사령관 통계',
    'No data': '데이터가 없습니다',
    'Ranking: ': '계급',
    'commander_warplane': '전투기',
};