pt_dict={    'commander_power': 'Poder',
    'commander_kill': 'Matar',
    'commander_city': 'Cidade',
    'commander_officer': 'Policial',
    'commander_titan': 'Titã',
    'commander_island': 'Ilha',
    'commander_merit': 'Mérito',
    'commander_level': 'Nível',
    'commander_ke_frenzy': 'Evento de Kill Frenzy',
    'commander_sc_frenzy': 'Evento de frenesi',
    'commander_ke_void': 'Evento Void Kill',
    'commander_sc_void': 'Evento vazio',
    'alliance_power': 'Poder',
    'alliance_kill': 'Matar',
    'alliance_territory': 'Território',
    'alliance_elite': 'Elite',
    'alliance_sc_frenzy': 'Evento de frenesi',
    'alliance_sc_void': 'Evento vazio',
    'Commander Name': 'Nome do comandante',
    'Alliance Name': 'Nome da aliança',
    'Commander Ranking': 'Classificação do comandante',
    'Alliance Ranking': 'Classificação da aliança',
    'Strongest Commander': 'Comandante mais forte',
    'Event': 'Evento',
    'Date': 'Data',
    'Opponent': 'Adversário',
    'Opponent score': 'Pontuação do oponente',
    'Nation score': 'Pontuação nacional',
    'Result': 'Resultado',
    'Win': 'Ganhar',
    'Lost': 'Perdido',
    'Strongest Commander Events': 'Eventos de comandantes mais fortes',
    'void': 'Vazio',
    'frenzy': 'Frenesi',
    'Search: ': 'Procurar:',
    'Ranking: ': 'Ranking:',
    'Clear graph': 'Gráfico limpo',
    'Reset graph': 'Redefinir gráfico',
    'Clear name': 'Excluir nome',
    'Void cycle update': 'Atualização do ciclo vazio',
    'Frenzy cycle update': 'Atualização do ciclo de frenesi',
    'name : xxx kills': '{0}: {1} mata',
    'name : merit_rank': '{0}: {1}',
    'name : city_level': '{0}: {1}',
    'name reached xxx officer power': '{0} alcançado {1} poder',
    'name reached xxx titan power': '{0} alcançado {1} poder',
    'name reached xxx warplane power': '{0} alcançado {1} poder',
    'Officer power': 'Poder de oficial',
    'Titan power': 'Titan Power',
    'City level upgrade': 'Atualização do nível da cidade',
    'Promotions': 'Promoções',
    'Top killers': 'Principais assassinos',
    'Recruit': 'Recrutar',
    'Private': 'Privado',
    'Private First Class': 'Primeira classe privada',
    'Sergeant': 'Sargento',
    'Master Sergeant': 'Mestre sargento',
    'Warrant Officer': 'Subtenente',
    'Second Lieutenant': 'Segundo tenente',
    'First Lieutenant': 'Primeiro-tenente',
    'Captain': 'Capitão',
    'Major': 'Principal',
    'Lieutenant Colonel': 'tenente-coronel',
    'Colonel': 'Coronel',
    'Brigadier': 'Brigadeiro',
    'General': 'Em geral',
    'General of the Army': 'General do Exército',
    'No data for this cycle': 'Sem dados para este ciclo',
    'Commander Strength': 'Estatística do comandante',
    'No data': 'Sem dados',
    'Ranking: ': 'Classificação',
    'commander_warplane': 'Plano de guerra',
    'commander_reputation': 'Reputação',
    'commander_loss': 'Perda',
    'Top void killers': 'Top Void Killers',
    'Select World': 'Selecione sua nação',
};