ru_dict={    'commander_power': 'Власть',
    'commander_kill': 'Убийство',
    'commander_city': 'Город',
    'commander_officer': 'Офицер',
    'commander_titan': 'Титан',
    'commander_island': 'Остров',
    'commander_merit': 'Цена',
    'commander_level': 'Уровень',
    'commander_ke_frenzy': 'Событие Frenzy Kill',
    'commander_sc_frenzy': 'Безумби',
    'commander_ke_void': 'Evoid Kill Event',
    'commander_sc_void': 'Void событие',
    'alliance_power': 'Власть',
    'alliance_kill': 'Убийство',
    'alliance_territory': 'Территория',
    'alliance_elite': 'Элита',
    'alliance_sc_frenzy': 'Безумби',
    'alliance_sc_void': 'Void событие',
    'Commander Name': 'Командир имя',
    'Alliance Name': 'Имя альянса',
    'Commander Ranking': 'Командир рейтинг',
    'Alliance Ranking': 'Рейтинг альянса',
    'Strongest Commander': 'Самый сильный командир',
    'Event': 'Событие',
    'Date': 'Дата',
    'Opponent': 'Противник',
    'Opponent score': 'Оценка противника',
    'Nation score': 'Национальный счет',
    'Result': 'Результат',
    'Win': 'Победить',
    'Lost': 'Потерянный',
    'Strongest Commander Events': 'Самые сильные командиры',
    'void': 'Пустота',
    'frenzy': 'Безумие',
    'Search: ': 'Поиск:',
    'Ranking: ': 'Рейтинг:',
    'Clear graph': 'Четкий график',
    'Reset graph': 'Сбросить график',
    'Clear name': 'Удалить имя',
    'Void cycle update': 'Обновление цикла пустоты',
    'Frenzy cycle update': 'Обновление цикла безумного',
    'name : xxx kills': '{0}: {1} убивает',
    'name : merit_rank': '{0}: {1}',
    'name : city_level': '{0}: {1}',
    'name reached xxx officer power': '{0} достиг {1} офицерская власть',
    'name reached xxx titan power': '{0} достиг {1} Power Titan',
    'Officer power': 'Офицерская власть',
    'Titan power': 'Сила Титана',
    'City level upgrade': 'Повышение уровня города',
    'Promotions': 'Акции',
    'Top killers': 'Лучшие убийцы',
    'Recruit': 'Нанимать на работу',
    'Private': 'Частный',
    'Private First Class': 'Частный первый класс',
    'Sergeant': 'Сержант',
    'Master Sergeant': 'Старшина',
    'Warrant Officer': 'Мичман',
    'Second Lieutenant': 'Второй лейтенант',
    'First Lieutenant': 'Первый лейтенант',
    'Captain': 'Капитан',
    'Major': 'Главный',
    'Lieutenant Colonel': 'лейтенант полковник',
    'Colonel': 'Полковник',
    'Brigadier': 'Бригадный',
    'General': 'Общий',
    'General of the Army': 'Генерал армии',
    'No data for this cycle': 'Нет данных для этого цикла',
    'Commander Strength': 'Командующий статистика',
    'No data': 'Нет данных',
    'Ranking: ': 'Классифицировать',
};